In [17]:
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors, AllChem, Lipinski, Fragments
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import cross_val_score, cross_val_predict, StratifiedKFold
from sklearn.metrics import roc_auc_score, classification_report, confusion_matrix, accuracy_score
import DataPreprocessing as dprep
from sklearn.impute import SimpleImputer
import DescriptionFeaturesSelection as dsf

In [7]:
training_data_path = 'training_smiles.csv'
test_data_path = 'test_smiles.csv'

training_data = pd.read_csv(training_data_path, dtype = {'ACTIVE': int})
test_data = pd.read_csv(test_data_path)

In [8]:
def extract_fingerprints(smiles):
    mol = Chem.MolFromSmiles(smiles)

    features = {}

    # Try nBits 2048, 1024, 512, 256
    # Morgan Fingerprint
    morgan_fp = AllChem.GetMorganFingerprintAsBitVect(mol, 2, nBits=512)
    for i in range(512):
        features[f'fp_{i}'] = morgan_fp[i]

    return features


    
training_features_df = training_data['SMILES'].apply(extract_fingerprints)

training_features_df = training_features_df.apply(pd.Series)

training_data_fingerprint = training_data.join(training_features_df)

training_data_fingerprint.to_csv('training_data_fingerprint.csv', index=False)


[11:47:46] WARNING: not removing hydrogen atom without neighbors


In [9]:

def extract_features(smiles):

    mol = Chem.MolFromSmiles(smiles)

    features = {}

    # Basic Properties
    features['num_atoms'] = mol.GetNumAtoms()
    features['num_bonds'] = mol.GetNumBonds()
    features['num_rings'] = mol.GetRingInfo().NumRings()

    # Molecular Descriptors
    for desc_name, desc_func in Descriptors.descList:
        features[desc_name] = desc_func(mol)

    # Lipinski Descriptors
    features['num_rotatable_bonds'] = Lipinski.NumRotatableBonds(mol)
    features['num_aromatic_rings'] = Lipinski.NumAromaticRings(mol)
    features['num_heteroatoms'] = Lipinski.NumHeteroatoms(mol)
    features['num_heavy_atoms'] = Lipinski.HeavyAtomCount(mol)
    features['num_h_donors'] = Lipinski.NumHDonors(mol)
    features['num_h_acceptors'] = Lipinski.NumHAcceptors(mol)
    features['num_aliphatic_rings'] = Lipinski.NumAliphaticRings(mol)
    features['num_saturated_rings'] = Lipinski.NumSaturatedRings(mol)
    features['num_aromatic_heterocycles'] = Lipinski.NumAromaticHeterocycles(mol)
    features['num_aromatic_carbocycles'] = Lipinski.NumAromaticCarbocycles(mol)
    features['num_aliphatic_heterocycles'] = Lipinski.NumAliphaticHeterocycles(mol)
    features['num_aliphatic_carbocycles'] = Lipinski.NumAliphaticCarbocycles(mol)

    # Fragment Descriptors
    for frag_func in dir(Fragments):
        if frag_func.startswith('fr_'):
            features[frag_func] = getattr(Fragments, frag_func)(mol)


    return features

training_features_df = training_data['SMILES'].apply(extract_features)

training_features_df = training_features_df.apply(pd.Series)

training_data_features = training_data.join(training_features_df)

training_data_features.to_csv('training_data_features.csv', index=False)



[12:30:17] WARNING: not removing hydrogen atom without neighbors
[12:30:17] WARNING: not removing hydrogen atom without neighbors
[12:30:17] WARNING: not removing hydrogen atom without neighbors


In [6]:
""" # Load the datasets
fingerprint_df = pd.read_csv('training_data_fingerprint.csv')
other_features_df = pd.read_csv('training_data_207_features.csv')

# Combine datasets
combined_df = pd.concat([fingerprint_df, other_features_df], axis=1) """

training_data = pd.read_csv('csvData/training_merged_fingerprints207.csv')

training_data, column_filter = dprep.create_column_filter(training_data)
training_data, imputation = dprep.create_imputation(training_data)


# Select only numeric columns for imputation
#numeric_cols = combined_df.select_dtypes(include=[np.number]).columns
#numeric_df = combined_df[numeric_cols]

#simple_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
#numeric_df_imputed = pd.DataFrame(simple_imputer.fit_transform(numeric_df), columns=numeric_df.columns)


#training_data = pd.concat([combined_df.drop(columns=numeric_cols), numeric_df_imputed], axis=1)


X = training_data.drop(columns=["INDEX", "ACTIVE"])
y = training_data["ACTIVE"]


In [7]:
rf_clf = RandomForestClassifier(n_estimators=100, random_state=42)

rf_clf.fit(X, y)

importances = rf_clf.feature_importances_

feature_importance_df = pd.DataFrame({
    'Feature': X.columns,
    'Importance': importances
})

feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

feature_importance_df.to_csv('feature_importances.csv', index=False)

print(feature_importance_df.head())


               Feature  Importance
537       BCUT2D_MRLOW    0.009636
512  MaxAbsEStateIndex    0.008735
515     MinEStateIndex    0.008680
514  MinAbsEStateIndex    0.008660
513     MaxEStateIndex    0.008062


In [18]:
def manual_crossValidation(training, training_lables, number_of_features = 50, use_classifier="randomForest", sampling="smote"):
    if use_classifier == "randomForest":
        classifier = RandomForestClassifier(bootstrap=True, max_depth=40, min_samples_leaf=2,min_samples_split=2,n_estimators=200,class_weight="balanced",random_state=42)
    elif use_classifier == "MLP":
        classifier = MLPClassifier(activation = 'relu',alpha= 0.0001, hidden_layer_sizes=(50,))
    else:
        print("Invalid classifier specified:")
        return
    
    X = training.copy()
    y = training_lables.copy()

    # Set up cross-validation
    kf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    accuracies = []
    auc_scores = []
    confusion_matrices = []

    for train_index, test_index in kf.split(X, y):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y.iloc[train_index], y.iloc[test_index]

        n_best_features = dsf.select_n_best_features_randomForestImportance(X_train, y_train, n_features=number_of_features) ## should be moved into the fold calculation loop
        X_train = X_train[list(n_best_features.keys())]
        X_test = X_test[list(n_best_features.keys())]


        if sampling=="smote":
            # Apply SMOTE to the training set
            smote = SMOTE(sampling_strategy='auto', random_state=42)
            X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)
        elif sampling=="under":
            X_train_resampled, y_train_resampled = new_balance_labels_down(X_train, y_train)
        else:
            X_train_resampled, y_train_resampled = X_train, y_train

        classifier.fit(X_train_resampled, y_train_resampled)
        y_pred = classifier.predict(X_test)

        accuracy = accuracy_score(y_test, y_pred)
        auc_score = roc_auc_score(y_test, classifier.predict_proba(X_test)[:, 1])
        cm = confusion_matrix(y_test, y_pred)

        accuracies.append(accuracy)
        auc_scores.append(auc_score)
        confusion_matrices.append(cm)

    avg_auc_score = np.mean(auc_scores)
    avg_confusion_matrix = np.mean(confusion_matrices, axis=0)
    class_report = classification_report(y_test, y_pred)

    return {
        'average_auc_score': avg_auc_score,
        'confusion_matrix': avg_confusion_matrix,
        'classification_report': class_report
    }

In [20]:
num_features_list = [10, 30, 50, 80, 100, len(X.columns)]

for num_features in num_features_list:
    ## Testing Random forest with and without smote
    results_oversampled = manual_crossValidation(X, y, num_features,use_classifier='randomForest',sampling="smote")
    results_undersampled = manual_crossValidation(X, y, num_features,use_classifier='randomForest',sampling="under")

    print("Random-Forest with SMOTE: ", results_oversampled["average_auc_score"])
    print("Random-Forest no SMOTE: ", results_undersampled["average_auc_score"])

    ## Testing MLP with and without smote
    MLP_results_oversampled = manual_crossValidation(training, training_lables, num_features,use_classifier='MLP', sampling="smote")
    MLP_results_undersampled = manual_crossValidation(training, training_lables, num_features, use_classifier='MLP',sampling="under")

    print("MLP with SMOTE: ", MLP_results_oversampled["average_auc_score"])
    print("MLP no SMOTE: ", MLP_results_undersampled["average_auc_score"])

In [49]:
# Evaluate without SMOTE
results_without_SMOTE = evaluate_model(X, y, rf_clf, num_features_list, use_smote=False)

print("Results without SMOTE")
for key, value in results_without_SMOTE.items():
    print(key, ":", value)


Confusion Matrix:
[[151414     32]
 [  1742     42]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99    151446
           1       0.57      0.02      0.05      1784

    accuracy                           0.99    153230
   macro avg       0.78      0.51      0.52    153230
weighted avg       0.98      0.99      0.98    153230


AUC-ROC Score: 0.7166547867940201
Confusion Matrix:
[[151426     20]
 [  1743     41]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      1.00      0.99    151446
           1       0.67      0.02      0.04      1784

    accuracy                           0.99    153230
   macro avg       0.83      0.51      0.52    153230
weighted avg       0.98      0.99      0.98    153230


AUC-ROC Score: 0.7661129132946143
Confusion Matrix:
[[151426     20]
 [  1743     41]]

Classification Report:
              precision    recall  f1-score  

In [50]:
# Evaluate with SMOTE
results_with_SMOTE = evaluate_model(X, y, rf_clf, num_features_list, use_smote=True)

print("\nResults with SMOTE")
for key, value in results_with_SMOTE.items():
    print(key, ":", value)

Confusion Matrix:
[[149605   1841]
 [  1138 150308]]

Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99    151446
           1       0.99      0.99      0.99    151446

    accuracy                           0.99    302892
   macro avg       0.99      0.99      0.99    302892
weighted avg       0.99      0.99      0.99    302892


AUC-ROC Score: 0.9993570208781507
Confusion Matrix:
[[150762    684]
 [   468 150978]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00    151446
           1       1.00      1.00      1.00    151446

    accuracy                           1.00    302892
   macro avg       1.00      1.00      1.00    302892
weighted avg       1.00      1.00      1.00    302892


AUC-ROC Score: 0.9998507236534854
Confusion Matrix:
[[151051    395]
 [   298 151148]]

Classification Report:
              precision    recall  f1-score  